Settings As screen:
    OnVisible: =Set(VarIcon12_1Visible, false);Set(VarIcon12_2Visible, true);Set(VarTextInput1DisplayMode, DisplayMode.Disabled)

    RectQuickActionBar1_3 As rectangle:
        Fill: =RGBA(0, 94, 146, 1)
        Height: =80
        Width: =Parent.Width
        ZIndex: =1

    LblAppName1_3 As label:
        Fill: =RGBA(58, 58, 58, 0)
        FontWeight: =FontWeight.Semibold
        Height: =80
        Size: =27
        Text: ="Settings"
        Width: =280
        Wrap: =false
        X: =80
        ZIndex: =2

    Rectangle2_6 As rectangle:
        Fill: =RGBA(0, 94, 146, 1)
        Height: =80
        Width: =640
        Y: =1060
        ZIndex: =3

    Icon8_6 As icon.Home:
        AccessibleLabel: ="Home"
        Color: =RGBA(255, 255, 255, 1)
        Height: =56
        Icon: =Icon.Home
        OnSelect: =Navigate(UI,ScreenTransition.Fade)
        TabIndex: =
        Width: =56
        X: =60
        Y: =1073
        ZIndex: =4

    Icon11_6 As icon.Print:
        AccessibleLabel: ="Detail"
        Color: =RGBA(255, 255, 255, 1)
        Height: =56
        Icon: =Icon.DocumentWithContent
        OnSelect: =Navigate(DetailScreen1,ScreenTransition.None)
        TabIndex: =
        Width: =56
        X: =408
        Y: =1073
        ZIndex: =5

    IconAccept1_2 As icon.Check:
        AccessibleLabel: =Self.Tooltip
        Height: =50
        Icon: =Icon.Check
        OnSelect: =Back()
        TabIndex: =0
        Tooltip: ="Submit item"
        Width: =50
        X: =570
        Y: =15
        ZIndex: =6

    Icon7_17 As icon.Mail:
        AccessibleLabel: ="Mail"
        AutoDisableOnSelect: =false
        Color: =RGBA(255, 255, 255, 1)
        Height: =56
        Icon: =Icon.Mail
        OnSelect: =Navigate(MailQuery)
        TabIndex: =
        Visible: =QueryMail2
        Width: =56
        X: =524
        Y: =1073
        ZIndex: =7

    Label3_4 As label:
        FontWeight: =FontWeight.Bold
        Height: =70
        Size: =22
        Text: ="Default Label Template"
        Width: =240
        X: =38
        Y: =135
        ZIndex: =8

    Menu_Navigation_8 As group:
        Height: =5
        Width: =5
        X: =20
        Y: =20
        ZIndex: =8

        IconBackarrow1_19 As icon.ChevronLeft:
            AccessibleLabel: =Self.Tooltip
            AutoDisableOnSelect: =false
            Height: =80
            Icon: =Icon.Hamburger
            OnSelect: =Set(Navigation,true);Set(HN1,false);Set(HN2,true);Set(HN3,true)
            PaddingBottom: =15
            PaddingLeft: =15
            PaddingRight: =15
            PaddingTop: =15
            Tooltip: ="Navigation"
            Visible: =HN1
            Width: =80
            ZIndex: =31

        IconBackarrow1_18 As icon.ChevronLeft:
            AccessibleLabel: =Self.Tooltip
            AutoDisableOnSelect: =false
            Color: =RGBA(0, 94, 146, 1)
            Height: =80
            Icon: =Icon.Cancel
            OnSelect: =Set(Navigation,false);Set(HN2,false);Set(HN1,true);Set(HN3,false)
            PaddingBottom: =15
            PaddingLeft: =15
            PaddingRight: =15
            PaddingTop: =15
            Rotation: =90
            Tooltip: ="Navigation"
            Visible: =HN2
            Width: =80
            ZIndex: =32

    Dropdown2_1 As dropdown:
        BorderColor: =RGBA(0, 94, 146, 1)
        ChevronBackground: =RGBA(0, 94, 146, 1)
        Default: ="UID"
        Height: =63
        Items: =["QuickTrack","DataMax","UID"]
        Size: =21
        Width: =284
        X: =306
        Y: =139
        ZIndex: =9

    Toggle1_1 As toggleSwitch:
        AccessibleLabel: ="Reel/Box"
        BorderStyle: =BorderStyle.None
        Default: =
        FalseText: ="Web - Page"
        FocusedBorderThickness: =0
        Height: =45
        OnCheck: =true
        Size: =21
        TrueFill: =RGBA(0, 94, 146, 1)
        TrueText: ="Application"
        Width: =240
        X: =156
        Y: =275
        ZIndex: =10

    Label3_6 As label:
        FontWeight: =FontWeight.Bold
        Height: =70
        Size: =22
        Text: ="Mode"
        Width: =118
        X: =38
        Y: =263
        ZIndex: =11

    Slider1 As slider:
        Default: =
        FocusedBorderThickness: =0
        HandleSize: =30
        Height: =70
        ValueFill: =RGBA(0, 96, 146, 1)
        Width: =370
        X: =220
        Y: =383
        ZIndex: =12

    Label3_7 As label:
        FontWeight: =FontWeight.Bold
        Height: =70
        Size: =22
        Text: ="Scan Rate"
        Width: =268
        X: =38
        Y: =383
        ZIndex: =13

    Label3_8 As label:
        FontWeight: =FontWeight.Bold
        Height: =70
        Size: =22
        Text: ="Label Darkness"
        Width: =268
        X: =38
        Y: =613
        ZIndex: =14

    Rectangle23_2 As rectangle:
        BorderColor: =RGBA(0, 96, 146, 1)
        BorderThickness: =Slider1_1.Value*2
        Fill: =RGBA(0, 0, 0, 0)
        Height: =150
        OnSelect: =Set(varPrintTriggered4, true);Navigate(Label_test)
        Width: =444
        X: =146
        Y: =712
        ZIndex: =15

    Rectangle23_3 As rectangle:
        BorderColor: =RGBA(0, 96, 146, 1)
        BorderThickness: =Slider1_1.Value*2
        Fill: =RGBA(0, 0, 0, 0)
        Height: =130
        OnSelect: =Set(varPrintTriggered4, true);Navigate(Label_test)
        Width: =424
        X: =156
        Y: =722
        ZIndex: =16

    Label3_9 As label:
        Align: =Align.Center
        FontWeight: =If(Slider1_1.Value = 1, FontWeight.Lighter,If(Slider1_1.Value = 2, FontWeight.Normal,If(Slider1_1.Value = 3, FontWeight.Semibold,If(Slider1_1.Value = 4, FontWeight.Bold))))
        Height: =120
        OnSelect: =Set(varPrintTriggered4, true);Navigate(Label_test)
        Size: =100
        Text: ="TEST"
        Width: =350
        X: =193
        Y: =722
        ZIndex: =17

    Label3_10 As label:
        FontWeight: =FontWeight.Bold
        Height: =70
        Size: =22
        Text: ="Password"
        Width: =268
        X: =38
        Y: =934
        ZIndex: =18

    TextInput1 As text:
        BorderColor: =RGBA(0, 94, 146, 1)
        Default: ="User@WISA"
        DisplayMode: =VarTextInput1DisplayMode
        Height: =70
        Size: =21
        Width: =377
        X: =213
        Y: =934
        ZIndex: =19

    Rectangle5_1 As rectangle:
        Fill: =RGBA(0, 96, 146, 1)
        Height: =70
        Width: =76
        X: =514
        Y: =934
        ZIndex: =20

    Icon12_1 As icon.Check:
        AccessibleLabel: ="Submit"
        Color: =RGBA(255, 255, 255, 1)
        Height: =70
        Icon: =Icon.Check
        OnSelect: =Set(VarTextInput1DisplayMode, DisplayMode.Disabled); Set(VarIcon12_2Visible, true);Set(VarIcon12_1Visible, false)
        PaddingBottom: =15
        PaddingLeft: =15
        PaddingRight: =15
        PaddingTop: =15
        TabIndex: =
        Visible: =VarIcon12_1Visible
        Width: =75
        X: =515
        Y: =934
        ZIndex: =21

    Icon12_2 As icon.Check:
        AccessibleLabel: ="Submit"
        Color: =RGBA(255, 255, 255, 1)
        Height: =70
        Icon: =Icon.Reset
        OnSelect: =Set(VarTextInput1DisplayMode, DisplayMode.Edit); Set(VarIcon12_1Visible, true);Set(VarIcon12_2Visible, false)
        PaddingBottom: =15
        PaddingLeft: =15
        PaddingRight: =15
        PaddingTop: =15
        TabIndex: =
        Visible: =VarIcon12_2Visible
        Width: =75
        X: =515
        Y: =934
        ZIndex: =22

    Slider1_1 As slider:
        Default: =2
        FocusedBorderThickness: =0
        HandleSize: =30
        Height: =150
        Layout: =Layout.Vertical
        Max: =4
        Min: =1
        ValueFill: =RGBA(0, 96, 146, 1)
        Width: =162
        Y: =712
        ZIndex: =23

    Menu_8 As group:
        Height: =5
        Width: =5
        X: =20
        Y: =20
        ZIndex: =32

        Rectangle7_8 As rectangle:
            BorderColor: =RGBA(0, 94, 146, 1)
            Fill: =RGBA(255, 255, 255, 1)
            Height: =560
            OnSelect: =Navigate(App_Details)
            Visible: =Navigation
            Width: =300
            ZIndex: =24

        Label7_49 As label:
            FontWeight: =FontWeight.Semibold
            Height: =80
            HoverColor: =RGBA(255,255,255,1)
            HoverFill: =RGBA(102, 102, 102, 1)
            OnSelect: =Set(AboutVisible,true);Set(Header,"About");Set(Navigation,false);Set(HN2,false);Set(HN1,true);Set(HN3,false);Set(I1V,false);Set(I2V,false);Set(I3V,false);Set(I4V,false);Set(I5V,false);Set(I6V,false);Set(I7V,false);Set(I8V,false);Set(I9V,false);Set(C1V,false);Set(C2V,false);Set(C3V,false);Set(H1V,false);Set(H2V,false);Set(H3V,false);Set(H4V,false);Set(H5V,false);Set(H6V,false);Set(H7V,false);Set(H8V,false);Set(G1V,false);Set(G2V,false);Set(G3V,false);Set(G4V,false);Set(G5V,false);Set(G6V,false);Set(G7V,false);Set(G8V,false);Set(G9V,false);Set(G10V,false);Set(G11V,false);Set(G12V,false);Set(G13V,false);Set(G14V,false);Set(G15V,false);Set(G16V,false);Set(U1V,false);Set(DisplayPopup1,false);Navigate(App_Details)
            PaddingLeft: =40
            PressedColor: =RGBA(255, 255, 255, 1)
            PressedFill: =RGBA(0, 94, 146, 1)
            Size: =24
            Text: ="About"
            Visible: =HN3
            Width: =300
            Y: =80
            ZIndex: =25

        Label7_50 As label:
            FontWeight: =FontWeight.Semibold
            Height: =80
            HoverColor: =RGBA(255,255,255,1)
            HoverFill: =RGBA(102, 102, 102, 1)
            OnSelect: =Set(AboutVisible,false);Set(Header,"Instructions");Set(Navigation,false);Set(HN2,false);Set(HN1,true);Set(HN3,false);Set(I1V,true);Set(I2V,false);Set(I3V,false);Set(I4V,false);Set(I5V,false);Set(I6V,false);Set(I7V,false);Set(I8V,false);Set(I9V,false);Set(C1V,false);Set(C2V,false);Set(C3V,false);Set(H1V,false);Set(H2V,false);Set(H3V,false);Set(H4V,false);Set(H5V,false);Set(H6V,false);Set(H7V,false);Set(H8V,false);Set(G1V,false);Set(G2V,false);Set(G3V,false);Set(G4V,false);Set(G5V,false);Set(G6V,false);Set(G7V,false);Set(G8V,false);Set(G9V,false);Set(G10V,false);Set(G11V,false);Set(G12V,false);Set(G13V,false);Set(G14V,false);Set(G15V,false);Set(G16V,false);Set(U1V,false);Set(Close1,false);Set(ContextPopup1,false);Set(AI1,false);Set(DisplayPopup1,false);Navigate(App_Details)
            PaddingLeft: =40
            PressedColor: =RGBA(255, 255, 255, 1)
            PressedFill: =RGBA(0, 94, 146, 1)
            Size: =24
            Text: ="Instructions"
            Visible: =HN3
            Width: =300
            Y: =160
            ZIndex: =26

        Label7_51 As label:
            FontWeight: =FontWeight.Semibold
            Height: =80
            HoverColor: =RGBA(255,255,255,1)
            HoverFill: =RGBA(102, 102, 102, 1)
            OnSelect: =Navigate(App_Details);Set(AboutVisible,false);Set(Header,"Configuration");Set(Navigation,false);Set(HN2,false);Set(HN1,true);Set(HN3,false);Set(C1V,true);Set(I1V,false);Set(I2V,false);Set(I3V,false);Set(I4V,false);Set(I5V,false);Set(I6V,false);Set(I7V,false);Set(I8V,false);Set(I9V,false);Set(C2V,false);Set(C3V,false);Set(H1V,false);Set(H2V,false);Set(H3V,false);Set(H4V,false);Set(H5V,false);Set(H6V,false);Set(H7V,false);Set(H8V,false);Set(G1V,false);Set(G2V,false);Set(G3V,false);Set(G4V,false);Set(G5V,false);Set(G6V,false);Set(G7V,false);Set(G8V,false);Set(G9V,false);Set(G10V,false);Set(G11V,false);Set(G12V,false);Set(G13V,false);Set(G14V,false);Set(G15V,false);Set(G16V,false);Set(U1V,false);Set(Close1,false);Set(ContextPopup1,false);Set(AI1,false);Set(DisplayPopup1,false)
            PaddingLeft: =40
            PressedColor: =RGBA(255, 255, 255, 1)
            PressedFill: =RGBA(0, 94, 146, 1)
            Size: =24
            Text: ="Configuration"
            Visible: =HN3
            Width: =300
            Y: =240
            ZIndex: =27

        Label7_52 As label:
            FontWeight: =FontWeight.Semibold
            Height: =80
            HoverColor: =RGBA(255,255,255,1)
            HoverFill: =RGBA(102, 102, 102, 1)
            OnSelect: =Navigate(App_Details);Set(AboutVisible,false);Set(Header,"Connectivity");Set(Navigation,false);Set(HN2,false);Set(HN1,true);Set(HN3,false);Set(I1V,false);Set(I2V,false);Set(I3V,false);Set(I4V,false);Set(I5V,false);Set(I6V,false);Set(I7V,false);Set(I8V,false);Set(I9V,false);Set(C1V,false);Set(C2V,false);Set(C3V,false);Set(H1V,true);Set(H2V,false);Set(H3V,false);Set(H4V,false);Set(H5V,false);Set(H6V,false);Set(H7V,false);Set(H8V,false);Set(G1V,false);Set(G2V,false);Set(G3V,false);Set(G4V,false);Set(G5V,false);Set(G6V,false);Set(G7V,false);Set(G8V,false);Set(G9V,false);Set(G10V,false);Set(G11V,false);Set(G12V,false);Set(G13V,false);Set(G14V,false);Set(G15V,false);Set(G16V,false);Set(U1V,false);Set(Close1,false);Set(ContextPopup1,false);Set(AI1,false);Set(DisplayPopup1,false)
            PaddingLeft: =40
            PressedColor: =RGBA(255, 255, 255, 1)
            PressedFill: =RGBA(0, 94, 146, 1)
            Size: =24
            Text: ="Connectivity"
            Visible: =HN3
            Width: =300
            Y: =320
            ZIndex: =28

        Label7_53 As label:
            FontWeight: =FontWeight.Semibold
            Height: =80
            HoverColor: =RGBA(255,255,255,1)
            HoverFill: =RGBA(102, 102, 102, 1)
            OnSelect: =Navigate(App_Details);Set(AboutVisible,false);Set(Header,"Guide");Set(Navigation,false);Set(HN2,false);Set(HN1,true);Set(HN3,false);Set(I1V,false);Set(I2V,false);Set(I3V,false);Set(I4V,false);Set(I5V,false);Set(I6V,false);Set(I7V,false);Set(I8V,false);Set(I9V,false);Set(C1V,false);Set(C2V,false);Set(C3V,false);Set(H1V,false);Set(H2V,false);Set(H3V,false);Set(H4V,false);Set(H5V,false);Set(H6V,false);Set(H7V,false);Set(H8V,false);Set(G1V,true);Set(G2V,false);Set(G3V,false);Set(G4V,false);Set(G5V,false);Set(G6V,false);Set(G7V,false);Set(G8V,false);Set(G9V,false);Set(G10V,false);Set(G11V,false);Set(G12V,false);Set(G13V,false);Set(G14V,false);Set(G15V,false);Set(G16V,false);Set(U1V,false);Set(Close1,false);Set(ContextPopup1,false);Set(AI1,false);Set(DisplayPopup1,false)
            PaddingLeft: =40
            PressedColor: =RGBA(255, 255, 255, 1)
            PressedFill: =RGBA(0, 94, 146, 1)
            Size: =24
            Text: ="Guide"
            Visible: =HN3
            Width: =300
            Y: =400
            ZIndex: =29

        Label7_54 As label:
            FontWeight: =FontWeight.Semibold
            Height: =80
            HoverColor: =RGBA(255,255,255,1)
            HoverFill: =RGBA(102, 102, 102, 1)
            OnSelect: =Navigate(Screen2);Set(AboutVisible,false);Set(Navigation,false);Set(HN2,false);Set(HN1,true);Set(HN3,false);
            PaddingLeft: =40
            PressedColor: =RGBA(255, 255, 255, 1)
            PressedFill: =RGBA(0, 94, 146, 1)
            Size: =24
            Text: ="Login"
            Visible: =HN3
            Width: =300
            Y: =480
            ZIndex: =30

    Header1_7 As Header:
        BasePaletteColor: =RGBA(0, 94, 146, 1)
        DisplayMode: =DisplayMode.Edit
        FontColor: =
        Height: =80
        IsLogoVisible: =false
        IsTitleVisible: =false
        OnSelectLogo: =false
        Style: ='Header.Style'.Neutral
        Title: =
        UserEmail: =User().Email
        UserImage: =User().Image
        UserName: =User().FullName
        Visible: =Navigation
        Width: =100
        X: =200
        Y: =0
        ZIndex: =33

    Icon9_6 As icon.Tray:
        AccessibleLabel: ="Bin"
        Color: =RGBA(255, 255, 255, 1)
        Height: =56
        Icon: =Icon.Items
        OnSelect: =Navigate(BrowseScreen1,ScreenTransition.None)
        TabIndex: =
        Width: =56
        X: =176
        Y: =1073
        ZIndex: =34

    Icon10_6 As icon.DocumentwithContent:
        AccessibleLabel: ="Tag"
        Color: =RGBA(255, 255, 255, 1)
        Height: =56
        Icon: =Icon.Tray
        OnSelect: =Navigate(Bin_Edit,ScreenTransition.None)
        TabIndex: =
        Width: =56
        X: =292
        Y: =1073
        ZIndex: =35

    Label3_11 As label:
        FontWeight: =FontWeight.Bold
        Height: =70
        Size: =22
        Text: ="Print Confirmation"
        Width: =290
        X: =38
        Y: =498
        ZIndex: =36

    Checkbox1 As checkbox:
        CheckboxBorderColor: =RGBA(0, 94, 146, 1)
        CheckboxSize: =80
        FocusedBorderThickness: =0
        Height: =85
        OnCheck: =Set(CheckBoxOption, "UID")
        OnUncheck: =Set(CheckBoxOption, "Manual")
        Reset: =
        Size: =21
        Text: =CheckBoxOption
        Width: =280
        X: =360
        Y: =489
        ZIndex: =37

